package:
  name: genome-sampler
  version: {{ PLUGIN_VERSION }}

source:
  path: ../..

build:
  script-env:
    - PLUGIN_VERSION
  script: make install

requirements:
  host:
    - python {{ python }}
    - setuptools

  run:
    - python {{ python }}
    - vsearch
    - pandas {{ pandas }}
    - qiime2 {{ qiime2_epoch }}.*
    - q2-types {{ qiime2_epoch }}.*
    - q2templates {{ qiime2_epoch }}.*
    - pyvcf

test:
  requires:
    - qiime2 >={{ qiime2 }}
    - q2-types >={{ q2_types }}

  imports:
    - genome_sampler
    - qiime2.plugins.genome_sampler

  commands:
    - py.test --pyargs genome_sampler

about:
  home: https://github.com/caporaso-lab/genome-sampler
  license: BSD-3-Clause
  license_family: BSD
